### PR TITLE
chore: update tree_sitter to new one

### PR DESCRIPTION
**Pull request by Decodetalkers**

### CODE REVIEW

**Comment by Decodetalkers** [comment]
@uyha

**Review by uyha — CHANGES_REQUESTED** [review]
`.editorconfig` and `.gitattributes` are not related to this PR, please remove them.

**Review by uyha — CHANGES_REQUESTED** [review]
I see that many files are not related to updating to new `tree-sitter`, please create a separate PR for this.

**Comment by Decodetalkers** [comment]
> I see that many files are not related to updating to new `tree-sitter`, please create a separate PR for this.

These are generated by new tree-sitter-cli

**Comment by uyha** [comment]
> These are generated by new tree-sitter-cli, not added by myself, Lol
lol, ok

**Pull request merged**
