### PR TITLE
Modifications to get nodes including parenthesis

### PR DESCRIPTION
**Pull request by gzmorell**
Adds a node with parenthesis. This is needed in helix-editor to allow match parenthesis to work.

### CODE REVIEW

**Comment by uyha** [comment]
I prefer "(" and ")" stay as annonymous nodes, is there a reason Helix can't match on annonymous nodes?

**Comment by gzmorell** [comment]
I first tried with anonymous node, "_paren_argument" instead of "paren_argument" and matching did not work in Helix. I don't know the reason. AFAIK other tree-sitter implementations have some node with parenthesis.  
- rust: "parameters: $ => seq(  '(', ...". 
- cpp: "parameter_list: $ => seq(  '(', ..."
- python: "parameters: $ => seq(  '(', ..."
- go: "parameter_list: $ => seq( '(', ..."

**Comment by uyha** [comment]
So I think the quotes being anonymous nodes is not the problem, hence I won't merge this PR. I will leave this PR open and please feel free to suggest changes if you found the underlying cause with Helix.

**Comment by gzmorell** [comment]
Just to be clear, with non-anonymous nodes, matching parenthesis works in Helix.

**Comment by uyha** [comment]
yes, I understand that, what I'm suggesting is you should discuss this issue with the Helix maintainers, and if they say that the problem is with the parentheses being anonymous nodes, then I will consider changing them to non-anonymous nodes.

**Comment by gzmorell** [comment]
I have been looking at Helix source. They use this function to iterate the nodes:
```let mut node = tree.root_node().named_descendant_for_byte_range(pos, pos)?;```
No idea why they use the named version.

**Comment by uyha** [comment]
an oversight, maybe?

**Comment by gzmorell** [comment]
I have testes with anonymous nodes and changing named_descendant with descendant, still not work.
Furthermore, testing the grammar for anonymous nodes, seems not to be easy.
"tree-sitter parse" only prints named nodes.

**Comment by uyha** [comment]
image

neovim has a feature for it and it's quite easy to set up for debugging if you need

**Comment by uyha** [comment]
@gzmorell  is this needed anymore? can you close it?

**Pull request closed without merging**
