### PR TITLE
refactor(pt2): use C for the external scanner

### PR DESCRIPTION
**Pull request by amaanq**
try `ts t` or `ts p <file>` and it should be fine now

### CODE REVIEW

**Comment by uyha** [comment]
I think `scan` needs to be `static` also and I don't think `inline` is needed

**Comment by uyha** [comment]
also `is_bracket_argument`

**Comment by uyha** [comment]
basically any functions that were in the anonymous namespace will have to be `static`

**Comment by amaanq** [comment]
The reason advance needs to be static is because (I believe) it conflicts with the lexer->advance function, so it is attempting to call itself, resulting in the segfault. I could be completely wrong of course. But the others dont need to be...but I can make them static anyways

**Comment by uyha** [comment]
Just to make them have the same semantic with the C++ file, in the C++ version, having them in the anonymous namespace make them have internal linkage, which makes sure they are not conflict with any other same name functions. Hence when switching to C, making them all `static` to have the same linkage. Also `inline` doesn't do anything here so plesae remove them.

**Comment by amaanq** [comment]
ok, done

**Comment by uyha** [comment]
you need to update the *binding.gyp* and *build.rs*

**Comment by amaanq** [comment]
done

**Pull request merged**
