### PR TITLE
fix(escape): \; should also be escape sequences

### PR DESCRIPTION
**Pull request by Decodetalkers**
Towards to
https://cmake.org/cmake/help/latest/manual/cmake-language.7.html, "\;"
is also escape sequences

Log: add ";" to escape sequences

### CODE REVIEW

**Comment by Decodetalkers** [comment]
o, ";" is not escape sequences, it is a keyword,

**Comment by Decodetalkers** [comment]
So ...

**Comment by uyha** [comment]
sorry, i was busy, can you also add tests for this?

**Comment by Decodetalkers** [comment]
> sorry, i was busy, can you also add tests for this?

Now the test is added

**Comment by uyha** [comment]
thanks for the PR

**Pull request merged**
